# Generated by Django 5.1 on 2024-08-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('finalizacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Interesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TimeField()),
                ('nivel', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogos_favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='imagens/')),
            ],
        ),
    ]
